channels:
  - conda-forge
dependencies:
  - appmode
  - pip:
    - pandas
    - matplotlib
    - numpy
    - seaborn
    - statsmodels
    - simple-crypt
    - openpyxl
    - scipy
    - glob
    - zipfile
